// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Request.proto

package com.cn.common.core.model.proto;

public final class RequestProto {
  private RequestProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum ModuleType
      implements com.google.protobuf.ProtocolMessageEnum {
    PLAYER(0, 1),
    CHAT(1, 2),
    ;
    
    public static final int PLAYER_VALUE = 1;
    public static final int CHAT_VALUE = 2;
    
    
    public final int getNumber() { return value; }
    
    public static ModuleType valueOf(int value) {
      switch (value) {
        case 1: return PLAYER;
        case 2: return CHAT;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<ModuleType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ModuleType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ModuleType>() {
            public ModuleType findValueByNumber(int number) {
              return ModuleType.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.cn.common.core.model.proto.RequestProto.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final ModuleType[] VALUES = {
      PLAYER, CHAT, 
    };
    
    public static ModuleType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private ModuleType(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:com.cn.common.core.model.ModuleType)
  }
  
  public enum CmdType
      implements com.google.protobuf.ProtocolMessageEnum {
    PUBLIC_CHAT(0, 11),
    PRIVATE_CHAT(1, 12),
    REGISTER_AND_LOGIN(2, 21),
    LOGIN(3, 22),
    PUSHCHAT(4, 101),
    ;
    
    public static final int PUBLIC_CHAT_VALUE = 11;
    public static final int PRIVATE_CHAT_VALUE = 12;
    public static final int REGISTER_AND_LOGIN_VALUE = 21;
    public static final int LOGIN_VALUE = 22;
    public static final int PUSHCHAT_VALUE = 101;
    
    
    public final int getNumber() { return value; }
    
    public static CmdType valueOf(int value) {
      switch (value) {
        case 11: return PUBLIC_CHAT;
        case 12: return PRIVATE_CHAT;
        case 21: return REGISTER_AND_LOGIN;
        case 22: return LOGIN;
        case 101: return PUSHCHAT;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<CmdType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<CmdType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CmdType>() {
            public CmdType findValueByNumber(int number) {
              return CmdType.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.cn.common.core.model.proto.RequestProto.getDescriptor().getEnumTypes().get(1);
    }
    
    private static final CmdType[] VALUES = {
      PUBLIC_CHAT, PRIVATE_CHAT, REGISTER_AND_LOGIN, LOGIN, PUSHCHAT, 
    };
    
    public static CmdType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private CmdType(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:com.cn.common.core.model.CmdType)
  }
  
  public interface ReqOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int32 HEADER_FLAG = 1 [default = 21415431];
    boolean hasHEADERFLAG();
    int getHEADERFLAG();
    
    // required .com.cn.common.core.model.ModuleType module = 2;
    boolean hasModule();
    com.cn.common.core.model.proto.RequestProto.ModuleType getModule();
    
    // required .com.cn.common.core.model.CmdType cmd = 3;
    boolean hasCmd();
    com.cn.common.core.model.proto.RequestProto.CmdType getCmd();
    
    // required bytes data = 4;
    boolean hasData();
    com.google.protobuf.ByteString getData();
  }
  public static final class Req extends
      com.google.protobuf.GeneratedMessage
      implements ReqOrBuilder {
    // Use Req.newBuilder() to construct.
    private Req(Builder builder) {
      super(builder);
    }
    private Req(boolean noInit) {}
    
    private static final Req defaultInstance;
    public static Req getDefaultInstance() {
      return defaultInstance;
    }
    
    public Req getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cn.common.core.model.proto.RequestProto.internal_static_com_cn_common_core_model_Req_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cn.common.core.model.proto.RequestProto.internal_static_com_cn_common_core_model_Req_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional int32 HEADER_FLAG = 1 [default = 21415431];
    public static final int HEADER_FLAG_FIELD_NUMBER = 1;
    private int hEADERFLAG_;
    public boolean hasHEADERFLAG() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getHEADERFLAG() {
      return hEADERFLAG_;
    }
    
    // required .com.cn.common.core.model.ModuleType module = 2;
    public static final int MODULE_FIELD_NUMBER = 2;
    private com.cn.common.core.model.proto.RequestProto.ModuleType module_;
    public boolean hasModule() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.cn.common.core.model.proto.RequestProto.ModuleType getModule() {
      return module_;
    }
    
    // required .com.cn.common.core.model.CmdType cmd = 3;
    public static final int CMD_FIELD_NUMBER = 3;
    private com.cn.common.core.model.proto.RequestProto.CmdType cmd_;
    public boolean hasCmd() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public com.cn.common.core.model.proto.RequestProto.CmdType getCmd() {
      return cmd_;
    }
    
    // required bytes data = 4;
    public static final int DATA_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString data_;
    public boolean hasData() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public com.google.protobuf.ByteString getData() {
      return data_;
    }
    
    private void initFields() {
      hEADERFLAG_ = 21415431;
      module_ = com.cn.common.core.model.proto.RequestProto.ModuleType.PLAYER;
      cmd_ = com.cn.common.core.model.proto.RequestProto.CmdType.PUBLIC_CHAT;
      data_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasModule()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCmd()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, hEADERFLAG_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, module_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, cmd_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, data_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, hEADERFLAG_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, module_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, cmd_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, data_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.cn.common.core.model.proto.RequestProto.Req parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.cn.common.core.model.proto.RequestProto.Req parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.cn.common.core.model.proto.RequestProto.Req parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.cn.common.core.model.proto.RequestProto.Req parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.cn.common.core.model.proto.RequestProto.Req parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.cn.common.core.model.proto.RequestProto.Req parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.cn.common.core.model.proto.RequestProto.Req parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.cn.common.core.model.proto.RequestProto.Req parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.cn.common.core.model.proto.RequestProto.Req parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.cn.common.core.model.proto.RequestProto.Req parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.cn.common.core.model.proto.RequestProto.Req prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.cn.common.core.model.proto.RequestProto.ReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cn.common.core.model.proto.RequestProto.internal_static_com_cn_common_core_model_Req_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cn.common.core.model.proto.RequestProto.internal_static_com_cn_common_core_model_Req_fieldAccessorTable;
      }
      
      // Construct using com.cn.common.core.model.proto.RequestProto.Req.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        hEADERFLAG_ = 21415431;
        bitField0_ = (bitField0_ & ~0x00000001);
        module_ = com.cn.common.core.model.proto.RequestProto.ModuleType.PLAYER;
        bitField0_ = (bitField0_ & ~0x00000002);
        cmd_ = com.cn.common.core.model.proto.RequestProto.CmdType.PUBLIC_CHAT;
        bitField0_ = (bitField0_ & ~0x00000004);
        data_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cn.common.core.model.proto.RequestProto.Req.getDescriptor();
      }
      
      public com.cn.common.core.model.proto.RequestProto.Req getDefaultInstanceForType() {
        return com.cn.common.core.model.proto.RequestProto.Req.getDefaultInstance();
      }
      
      public com.cn.common.core.model.proto.RequestProto.Req build() {
        com.cn.common.core.model.proto.RequestProto.Req result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.cn.common.core.model.proto.RequestProto.Req buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.cn.common.core.model.proto.RequestProto.Req result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.cn.common.core.model.proto.RequestProto.Req buildPartial() {
        com.cn.common.core.model.proto.RequestProto.Req result = new com.cn.common.core.model.proto.RequestProto.Req(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.hEADERFLAG_ = hEADERFLAG_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.module_ = module_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.cmd_ = cmd_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.data_ = data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cn.common.core.model.proto.RequestProto.Req) {
          return mergeFrom((com.cn.common.core.model.proto.RequestProto.Req)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.cn.common.core.model.proto.RequestProto.Req other) {
        if (other == com.cn.common.core.model.proto.RequestProto.Req.getDefaultInstance()) return this;
        if (other.hasHEADERFLAG()) {
          setHEADERFLAG(other.getHEADERFLAG());
        }
        if (other.hasModule()) {
          setModule(other.getModule());
        }
        if (other.hasCmd()) {
          setCmd(other.getCmd());
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasModule()) {
          
          return false;
        }
        if (!hasCmd()) {
          
          return false;
        }
        if (!hasData()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              hEADERFLAG_ = input.readInt32();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              com.cn.common.core.model.proto.RequestProto.ModuleType value = com.cn.common.core.model.proto.RequestProto.ModuleType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                module_ = value;
              }
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              com.cn.common.core.model.proto.RequestProto.CmdType value = com.cn.common.core.model.proto.RequestProto.CmdType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                cmd_ = value;
              }
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              data_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int32 HEADER_FLAG = 1 [default = 21415431];
      private int hEADERFLAG_ = 21415431;
      public boolean hasHEADERFLAG() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getHEADERFLAG() {
        return hEADERFLAG_;
      }
      public Builder setHEADERFLAG(int value) {
        bitField0_ |= 0x00000001;
        hEADERFLAG_ = value;
        onChanged();
        return this;
      }
      public Builder clearHEADERFLAG() {
        bitField0_ = (bitField0_ & ~0x00000001);
        hEADERFLAG_ = 21415431;
        onChanged();
        return this;
      }
      
      // required .com.cn.common.core.model.ModuleType module = 2;
      private com.cn.common.core.model.proto.RequestProto.ModuleType module_ = com.cn.common.core.model.proto.RequestProto.ModuleType.PLAYER;
      public boolean hasModule() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.cn.common.core.model.proto.RequestProto.ModuleType getModule() {
        return module_;
      }
      public Builder setModule(com.cn.common.core.model.proto.RequestProto.ModuleType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        module_ = value;
        onChanged();
        return this;
      }
      public Builder clearModule() {
        bitField0_ = (bitField0_ & ~0x00000002);
        module_ = com.cn.common.core.model.proto.RequestProto.ModuleType.PLAYER;
        onChanged();
        return this;
      }
      
      // required .com.cn.common.core.model.CmdType cmd = 3;
      private com.cn.common.core.model.proto.RequestProto.CmdType cmd_ = com.cn.common.core.model.proto.RequestProto.CmdType.PUBLIC_CHAT;
      public boolean hasCmd() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public com.cn.common.core.model.proto.RequestProto.CmdType getCmd() {
        return cmd_;
      }
      public Builder setCmd(com.cn.common.core.model.proto.RequestProto.CmdType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        cmd_ = value;
        onChanged();
        return this;
      }
      public Builder clearCmd() {
        bitField0_ = (bitField0_ & ~0x00000004);
        cmd_ = com.cn.common.core.model.proto.RequestProto.CmdType.PUBLIC_CHAT;
        onChanged();
        return this;
      }
      
      // required bytes data = 4;
      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasData() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        data_ = value;
        onChanged();
        return this;
      }
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000008);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.cn.common.core.model.Req)
    }
    
    static {
      defaultInstance = new Req(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.cn.common.core.model.Req)
  }
  
  public interface LoginOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string username = 1;
    boolean hasUsername();
    String getUsername();
    
    // required string password = 2;
    boolean hasPassword();
    String getPassword();
  }
  public static final class Login extends
      com.google.protobuf.GeneratedMessage
      implements LoginOrBuilder {
    // Use Login.newBuilder() to construct.
    private Login(Builder builder) {
      super(builder);
    }
    private Login(boolean noInit) {}
    
    private static final Login defaultInstance;
    public static Login getDefaultInstance() {
      return defaultInstance;
    }
    
    public Login getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cn.common.core.model.proto.RequestProto.internal_static_com_cn_common_core_model_Login_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cn.common.core.model.proto.RequestProto.internal_static_com_cn_common_core_model_Login_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string username = 1;
    public static final int USERNAME_FIELD_NUMBER = 1;
    private java.lang.Object username_;
    public boolean hasUsername() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getUsername() {
      java.lang.Object ref = username_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          username_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUsernameBytes() {
      java.lang.Object ref = username_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string password = 2;
    public static final int PASSWORD_FIELD_NUMBER = 2;
    private java.lang.Object password_;
    public boolean hasPassword() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          password_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      username_ = "";
      password_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasUsername()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPassword()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUsernameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getPasswordBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUsernameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getPasswordBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.cn.common.core.model.proto.RequestProto.Login parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.cn.common.core.model.proto.RequestProto.Login parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.cn.common.core.model.proto.RequestProto.Login parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.cn.common.core.model.proto.RequestProto.Login parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.cn.common.core.model.proto.RequestProto.Login parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.cn.common.core.model.proto.RequestProto.Login parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.cn.common.core.model.proto.RequestProto.Login parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.cn.common.core.model.proto.RequestProto.Login parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.cn.common.core.model.proto.RequestProto.Login parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.cn.common.core.model.proto.RequestProto.Login parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.cn.common.core.model.proto.RequestProto.Login prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.cn.common.core.model.proto.RequestProto.LoginOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cn.common.core.model.proto.RequestProto.internal_static_com_cn_common_core_model_Login_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cn.common.core.model.proto.RequestProto.internal_static_com_cn_common_core_model_Login_fieldAccessorTable;
      }
      
      // Construct using com.cn.common.core.model.proto.RequestProto.Login.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        username_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        password_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cn.common.core.model.proto.RequestProto.Login.getDescriptor();
      }
      
      public com.cn.common.core.model.proto.RequestProto.Login getDefaultInstanceForType() {
        return com.cn.common.core.model.proto.RequestProto.Login.getDefaultInstance();
      }
      
      public com.cn.common.core.model.proto.RequestProto.Login build() {
        com.cn.common.core.model.proto.RequestProto.Login result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.cn.common.core.model.proto.RequestProto.Login buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.cn.common.core.model.proto.RequestProto.Login result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.cn.common.core.model.proto.RequestProto.Login buildPartial() {
        com.cn.common.core.model.proto.RequestProto.Login result = new com.cn.common.core.model.proto.RequestProto.Login(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.username_ = username_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.password_ = password_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cn.common.core.model.proto.RequestProto.Login) {
          return mergeFrom((com.cn.common.core.model.proto.RequestProto.Login)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.cn.common.core.model.proto.RequestProto.Login other) {
        if (other == com.cn.common.core.model.proto.RequestProto.Login.getDefaultInstance()) return this;
        if (other.hasUsername()) {
          setUsername(other.getUsername());
        }
        if (other.hasPassword()) {
          setPassword(other.getPassword());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasUsername()) {
          
          return false;
        }
        if (!hasPassword()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              username_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              password_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string username = 1;
      private java.lang.Object username_ = "";
      public boolean hasUsername() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getUsername() {
        java.lang.Object ref = username_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          username_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUsername(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        username_ = value;
        onChanged();
        return this;
      }
      public Builder clearUsername() {
        bitField0_ = (bitField0_ & ~0x00000001);
        username_ = getDefaultInstance().getUsername();
        onChanged();
        return this;
      }
      void setUsername(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        username_ = value;
        onChanged();
      }
      
      // required string password = 2;
      private java.lang.Object password_ = "";
      public boolean hasPassword() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          password_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPassword(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        password_ = value;
        onChanged();
        return this;
      }
      public Builder clearPassword() {
        bitField0_ = (bitField0_ & ~0x00000002);
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      void setPassword(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        password_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:com.cn.common.core.model.Login)
    }
    
    static {
      defaultInstance = new Login(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.cn.common.core.model.Login)
  }
  
  public interface RegisterOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string username = 1;
    boolean hasUsername();
    String getUsername();
    
    // required string password = 2;
    boolean hasPassword();
    String getPassword();
  }
  public static final class Register extends
      com.google.protobuf.GeneratedMessage
      implements RegisterOrBuilder {
    // Use Register.newBuilder() to construct.
    private Register(Builder builder) {
      super(builder);
    }
    private Register(boolean noInit) {}
    
    private static final Register defaultInstance;
    public static Register getDefaultInstance() {
      return defaultInstance;
    }
    
    public Register getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cn.common.core.model.proto.RequestProto.internal_static_com_cn_common_core_model_Register_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cn.common.core.model.proto.RequestProto.internal_static_com_cn_common_core_model_Register_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string username = 1;
    public static final int USERNAME_FIELD_NUMBER = 1;
    private java.lang.Object username_;
    public boolean hasUsername() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getUsername() {
      java.lang.Object ref = username_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          username_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUsernameBytes() {
      java.lang.Object ref = username_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string password = 2;
    public static final int PASSWORD_FIELD_NUMBER = 2;
    private java.lang.Object password_;
    public boolean hasPassword() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          password_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      username_ = "";
      password_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasUsername()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPassword()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUsernameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getPasswordBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUsernameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getPasswordBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.cn.common.core.model.proto.RequestProto.Register parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.cn.common.core.model.proto.RequestProto.Register parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.cn.common.core.model.proto.RequestProto.Register parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.cn.common.core.model.proto.RequestProto.Register parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.cn.common.core.model.proto.RequestProto.Register parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.cn.common.core.model.proto.RequestProto.Register parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.cn.common.core.model.proto.RequestProto.Register parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.cn.common.core.model.proto.RequestProto.Register parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.cn.common.core.model.proto.RequestProto.Register parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.cn.common.core.model.proto.RequestProto.Register parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.cn.common.core.model.proto.RequestProto.Register prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.cn.common.core.model.proto.RequestProto.RegisterOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cn.common.core.model.proto.RequestProto.internal_static_com_cn_common_core_model_Register_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cn.common.core.model.proto.RequestProto.internal_static_com_cn_common_core_model_Register_fieldAccessorTable;
      }
      
      // Construct using com.cn.common.core.model.proto.RequestProto.Register.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        username_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        password_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cn.common.core.model.proto.RequestProto.Register.getDescriptor();
      }
      
      public com.cn.common.core.model.proto.RequestProto.Register getDefaultInstanceForType() {
        return com.cn.common.core.model.proto.RequestProto.Register.getDefaultInstance();
      }
      
      public com.cn.common.core.model.proto.RequestProto.Register build() {
        com.cn.common.core.model.proto.RequestProto.Register result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.cn.common.core.model.proto.RequestProto.Register buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.cn.common.core.model.proto.RequestProto.Register result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.cn.common.core.model.proto.RequestProto.Register buildPartial() {
        com.cn.common.core.model.proto.RequestProto.Register result = new com.cn.common.core.model.proto.RequestProto.Register(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.username_ = username_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.password_ = password_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cn.common.core.model.proto.RequestProto.Register) {
          return mergeFrom((com.cn.common.core.model.proto.RequestProto.Register)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.cn.common.core.model.proto.RequestProto.Register other) {
        if (other == com.cn.common.core.model.proto.RequestProto.Register.getDefaultInstance()) return this;
        if (other.hasUsername()) {
          setUsername(other.getUsername());
        }
        if (other.hasPassword()) {
          setPassword(other.getPassword());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasUsername()) {
          
          return false;
        }
        if (!hasPassword()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              username_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              password_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string username = 1;
      private java.lang.Object username_ = "";
      public boolean hasUsername() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getUsername() {
        java.lang.Object ref = username_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          username_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUsername(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        username_ = value;
        onChanged();
        return this;
      }
      public Builder clearUsername() {
        bitField0_ = (bitField0_ & ~0x00000001);
        username_ = getDefaultInstance().getUsername();
        onChanged();
        return this;
      }
      void setUsername(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        username_ = value;
        onChanged();
      }
      
      // required string password = 2;
      private java.lang.Object password_ = "";
      public boolean hasPassword() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          password_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPassword(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        password_ = value;
        onChanged();
        return this;
      }
      public Builder clearPassword() {
        bitField0_ = (bitField0_ & ~0x00000002);
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      void setPassword(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        password_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:com.cn.common.core.model.Register)
    }
    
    static {
      defaultInstance = new Register(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.cn.common.core.model.Register)
  }
  
  public interface MessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string username = 1;
    boolean hasUsername();
    String getUsername();
    
    // required string msg = 2;
    boolean hasMsg();
    String getMsg();
    
    // required string token = 3;
    boolean hasToken();
    String getToken();
    
    // optional string toUser = 4;
    boolean hasToUser();
    String getToUser();
    
    // optional string group = 5;
    boolean hasGroup();
    String getGroup();
  }
  public static final class Message extends
      com.google.protobuf.GeneratedMessage
      implements MessageOrBuilder {
    // Use Message.newBuilder() to construct.
    private Message(Builder builder) {
      super(builder);
    }
    private Message(boolean noInit) {}
    
    private static final Message defaultInstance;
    public static Message getDefaultInstance() {
      return defaultInstance;
    }
    
    public Message getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cn.common.core.model.proto.RequestProto.internal_static_com_cn_common_core_model_Message_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cn.common.core.model.proto.RequestProto.internal_static_com_cn_common_core_model_Message_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string username = 1;
    public static final int USERNAME_FIELD_NUMBER = 1;
    private java.lang.Object username_;
    public boolean hasUsername() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getUsername() {
      java.lang.Object ref = username_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          username_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUsernameBytes() {
      java.lang.Object ref = username_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string msg = 2;
    public static final int MSG_FIELD_NUMBER = 2;
    private java.lang.Object msg_;
    public boolean hasMsg() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getMsg() {
      java.lang.Object ref = msg_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          msg_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string token = 3;
    public static final int TOKEN_FIELD_NUMBER = 3;
    private java.lang.Object token_;
    public boolean hasToken() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getToken() {
      java.lang.Object ref = token_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          token_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string toUser = 4;
    public static final int TOUSER_FIELD_NUMBER = 4;
    private java.lang.Object toUser_;
    public boolean hasToUser() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getToUser() {
      java.lang.Object ref = toUser_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          toUser_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getToUserBytes() {
      java.lang.Object ref = toUser_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        toUser_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string group = 5;
    public static final int GROUP_FIELD_NUMBER = 5;
    private java.lang.Object group_;
    public boolean hasGroup() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getGroup() {
      java.lang.Object ref = group_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          group_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getGroupBytes() {
      java.lang.Object ref = group_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        group_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      username_ = "";
      msg_ = "";
      token_ = "";
      toUser_ = "";
      group_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasUsername()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMsg()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasToken()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUsernameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getMsgBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getTokenBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getToUserBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getGroupBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUsernameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getMsgBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getTokenBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getToUserBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getGroupBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.cn.common.core.model.proto.RequestProto.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.cn.common.core.model.proto.RequestProto.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.cn.common.core.model.proto.RequestProto.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.cn.common.core.model.proto.RequestProto.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.cn.common.core.model.proto.RequestProto.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.cn.common.core.model.proto.RequestProto.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.cn.common.core.model.proto.RequestProto.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.cn.common.core.model.proto.RequestProto.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.cn.common.core.model.proto.RequestProto.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.cn.common.core.model.proto.RequestProto.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.cn.common.core.model.proto.RequestProto.Message prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.cn.common.core.model.proto.RequestProto.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cn.common.core.model.proto.RequestProto.internal_static_com_cn_common_core_model_Message_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cn.common.core.model.proto.RequestProto.internal_static_com_cn_common_core_model_Message_fieldAccessorTable;
      }
      
      // Construct using com.cn.common.core.model.proto.RequestProto.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        username_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        msg_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        token_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        toUser_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        group_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cn.common.core.model.proto.RequestProto.Message.getDescriptor();
      }
      
      public com.cn.common.core.model.proto.RequestProto.Message getDefaultInstanceForType() {
        return com.cn.common.core.model.proto.RequestProto.Message.getDefaultInstance();
      }
      
      public com.cn.common.core.model.proto.RequestProto.Message build() {
        com.cn.common.core.model.proto.RequestProto.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.cn.common.core.model.proto.RequestProto.Message buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.cn.common.core.model.proto.RequestProto.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.cn.common.core.model.proto.RequestProto.Message buildPartial() {
        com.cn.common.core.model.proto.RequestProto.Message result = new com.cn.common.core.model.proto.RequestProto.Message(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.username_ = username_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.msg_ = msg_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.token_ = token_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.toUser_ = toUser_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.group_ = group_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cn.common.core.model.proto.RequestProto.Message) {
          return mergeFrom((com.cn.common.core.model.proto.RequestProto.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.cn.common.core.model.proto.RequestProto.Message other) {
        if (other == com.cn.common.core.model.proto.RequestProto.Message.getDefaultInstance()) return this;
        if (other.hasUsername()) {
          setUsername(other.getUsername());
        }
        if (other.hasMsg()) {
          setMsg(other.getMsg());
        }
        if (other.hasToken()) {
          setToken(other.getToken());
        }
        if (other.hasToUser()) {
          setToUser(other.getToUser());
        }
        if (other.hasGroup()) {
          setGroup(other.getGroup());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasUsername()) {
          
          return false;
        }
        if (!hasMsg()) {
          
          return false;
        }
        if (!hasToken()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              username_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              msg_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              token_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              toUser_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              group_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string username = 1;
      private java.lang.Object username_ = "";
      public boolean hasUsername() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getUsername() {
        java.lang.Object ref = username_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          username_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUsername(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        username_ = value;
        onChanged();
        return this;
      }
      public Builder clearUsername() {
        bitField0_ = (bitField0_ & ~0x00000001);
        username_ = getDefaultInstance().getUsername();
        onChanged();
        return this;
      }
      void setUsername(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        username_ = value;
        onChanged();
      }
      
      // required string msg = 2;
      private java.lang.Object msg_ = "";
      public boolean hasMsg() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getMsg() {
        java.lang.Object ref = msg_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          msg_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setMsg(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        msg_ = value;
        onChanged();
        return this;
      }
      public Builder clearMsg() {
        bitField0_ = (bitField0_ & ~0x00000002);
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      void setMsg(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        msg_ = value;
        onChanged();
      }
      
      // required string token = 3;
      private java.lang.Object token_ = "";
      public boolean hasToken() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getToken() {
        java.lang.Object ref = token_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          token_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setToken(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        token_ = value;
        onChanged();
        return this;
      }
      public Builder clearToken() {
        bitField0_ = (bitField0_ & ~0x00000004);
        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }
      void setToken(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        token_ = value;
        onChanged();
      }
      
      // optional string toUser = 4;
      private java.lang.Object toUser_ = "";
      public boolean hasToUser() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getToUser() {
        java.lang.Object ref = toUser_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          toUser_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setToUser(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        toUser_ = value;
        onChanged();
        return this;
      }
      public Builder clearToUser() {
        bitField0_ = (bitField0_ & ~0x00000008);
        toUser_ = getDefaultInstance().getToUser();
        onChanged();
        return this;
      }
      void setToUser(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        toUser_ = value;
        onChanged();
      }
      
      // optional string group = 5;
      private java.lang.Object group_ = "";
      public boolean hasGroup() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getGroup() {
        java.lang.Object ref = group_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          group_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setGroup(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        group_ = value;
        onChanged();
        return this;
      }
      public Builder clearGroup() {
        bitField0_ = (bitField0_ & ~0x00000010);
        group_ = getDefaultInstance().getGroup();
        onChanged();
        return this;
      }
      void setGroup(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        group_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:com.cn.common.core.model.Message)
    }
    
    static {
      defaultInstance = new Message(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.cn.common.core.model.Message)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_cn_common_core_model_Req_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_cn_common_core_model_Req_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_cn_common_core_model_Login_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_cn_common_core_model_Login_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_cn_common_core_model_Register_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_cn_common_core_model_Register_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_cn_common_core_model_Message_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_cn_common_core_model_Message_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rRequest.proto\022\030com.cn.common.core.mode" +
      "l\"\230\001\n\003Req\022\035\n\013HEADER_FLAG\030\001 \001(\005:\01021415431" +
      "\0224\n\006module\030\002 \002(\0162$.com.cn.common.core.mo" +
      "del.ModuleType\022.\n\003cmd\030\003 \002(\0162!.com.cn.com" +
      "mon.core.model.CmdType\022\014\n\004data\030\004 \002(\014\"+\n\005" +
      "Login\022\020\n\010username\030\001 \002(\t\022\020\n\010password\030\002 \002(" +
      "\t\".\n\010Register\022\020\n\010username\030\001 \002(\t\022\020\n\010passw" +
      "ord\030\002 \002(\t\"V\n\007Message\022\020\n\010username\030\001 \002(\t\022\013" +
      "\n\003msg\030\002 \002(\t\022\r\n\005token\030\003 \002(\t\022\016\n\006toUser\030\004 \001" +
      "(\t\022\r\n\005group\030\005 \001(\t*\"\n\nModuleType\022\n\n\006PLAYE",
      "R\020\001\022\010\n\004CHAT\020\002*]\n\007CmdType\022\017\n\013PUBLIC_CHAT\020" +
      "\013\022\020\n\014PRIVATE_CHAT\020\014\022\026\n\022REGISTER_AND_LOGI" +
      "N\020\025\022\t\n\005LOGIN\020\026\022\014\n\010PUSHCHAT\020eB.\n\036com.cn.c" +
      "ommon.core.model.protoB\014RequestProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_cn_common_core_model_Req_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_cn_common_core_model_Req_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_cn_common_core_model_Req_descriptor,
              new java.lang.String[] { "HEADERFLAG", "Module", "Cmd", "Data", },
              com.cn.common.core.model.proto.RequestProto.Req.class,
              com.cn.common.core.model.proto.RequestProto.Req.Builder.class);
          internal_static_com_cn_common_core_model_Login_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_cn_common_core_model_Login_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_cn_common_core_model_Login_descriptor,
              new java.lang.String[] { "Username", "Password", },
              com.cn.common.core.model.proto.RequestProto.Login.class,
              com.cn.common.core.model.proto.RequestProto.Login.Builder.class);
          internal_static_com_cn_common_core_model_Register_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_cn_common_core_model_Register_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_cn_common_core_model_Register_descriptor,
              new java.lang.String[] { "Username", "Password", },
              com.cn.common.core.model.proto.RequestProto.Register.class,
              com.cn.common.core.model.proto.RequestProto.Register.Builder.class);
          internal_static_com_cn_common_core_model_Message_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_com_cn_common_core_model_Message_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_cn_common_core_model_Message_descriptor,
              new java.lang.String[] { "Username", "Msg", "Token", "ToUser", "Group", },
              com.cn.common.core.model.proto.RequestProto.Message.class,
              com.cn.common.core.model.proto.RequestProto.Message.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
