// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Response.proto

package com.cn.common.core.model.proto;

public final class ResponseProto {
  private ResponseProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum ModuleType
      implements com.google.protobuf.ProtocolMessageEnum {
    PLAYER(0, 1),
    CHAT(1, 2),
    ;
    
    public static final int PLAYER_VALUE = 1;
    public static final int CHAT_VALUE = 2;
    
    
    public final int getNumber() { return value; }
    
    public static ModuleType valueOf(int value) {
      switch (value) {
        case 1: return PLAYER;
        case 2: return CHAT;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<ModuleType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ModuleType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ModuleType>() {
            public ModuleType findValueByNumber(int number) {
              return ModuleType.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.cn.common.core.model.proto.ResponseProto.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final ModuleType[] VALUES = {
      PLAYER, CHAT, 
    };
    
    public static ModuleType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private ModuleType(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:com.cn.common.core.model.ModuleType)
  }
  
  public enum CmdType
      implements com.google.protobuf.ProtocolMessageEnum {
    PUBLIC_CHAT(0, 11),
    PRIVATE_CHAT(1, 12),
    REGISTER_AND_LOGIN(2, 21),
    LOGIN(3, 22),
    PUSHCHAT(4, 101),
    ;
    
    public static final int PUBLIC_CHAT_VALUE = 11;
    public static final int PRIVATE_CHAT_VALUE = 12;
    public static final int REGISTER_AND_LOGIN_VALUE = 21;
    public static final int LOGIN_VALUE = 22;
    public static final int PUSHCHAT_VALUE = 101;
    
    
    public final int getNumber() { return value; }
    
    public static CmdType valueOf(int value) {
      switch (value) {
        case 11: return PUBLIC_CHAT;
        case 12: return PRIVATE_CHAT;
        case 21: return REGISTER_AND_LOGIN;
        case 22: return LOGIN;
        case 101: return PUSHCHAT;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<CmdType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<CmdType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CmdType>() {
            public CmdType findValueByNumber(int number) {
              return CmdType.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.cn.common.core.model.proto.ResponseProto.getDescriptor().getEnumTypes().get(1);
    }
    
    private static final CmdType[] VALUES = {
      PUBLIC_CHAT, PRIVATE_CHAT, REGISTER_AND_LOGIN, LOGIN, PUSHCHAT, 
    };
    
    public static CmdType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private CmdType(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:com.cn.common.core.model.CmdType)
  }
  
  public interface RspOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int32 HEADER_FLAG = 1 [default = 21415431];
    boolean hasHEADERFLAG();
    int getHEADERFLAG();
    
    // optional .com.cn.common.core.model.ModuleType module = 2;
    boolean hasModule();
    com.cn.common.core.model.proto.ResponseProto.ModuleType getModule();
    
    // optional .com.cn.common.core.model.CmdType cmd = 3;
    boolean hasCmd();
    com.cn.common.core.model.proto.ResponseProto.CmdType getCmd();
    
    // optional bytes data = 4;
    boolean hasData();
    com.google.protobuf.ByteString getData();
    
    // required int32 resultCode = 5;
    boolean hasResultCode();
    int getResultCode();
  }
  public static final class Rsp extends
      com.google.protobuf.GeneratedMessage
      implements RspOrBuilder {
    // Use Rsp.newBuilder() to construct.
    private Rsp(Builder builder) {
      super(builder);
    }
    private Rsp(boolean noInit) {}
    
    private static final Rsp defaultInstance;
    public static Rsp getDefaultInstance() {
      return defaultInstance;
    }
    
    public Rsp getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cn.common.core.model.proto.ResponseProto.internal_static_com_cn_common_core_model_Rsp_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cn.common.core.model.proto.ResponseProto.internal_static_com_cn_common_core_model_Rsp_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional int32 HEADER_FLAG = 1 [default = 21415431];
    public static final int HEADER_FLAG_FIELD_NUMBER = 1;
    private int hEADERFLAG_;
    public boolean hasHEADERFLAG() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getHEADERFLAG() {
      return hEADERFLAG_;
    }
    
    // optional .com.cn.common.core.model.ModuleType module = 2;
    public static final int MODULE_FIELD_NUMBER = 2;
    private com.cn.common.core.model.proto.ResponseProto.ModuleType module_;
    public boolean hasModule() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.cn.common.core.model.proto.ResponseProto.ModuleType getModule() {
      return module_;
    }
    
    // optional .com.cn.common.core.model.CmdType cmd = 3;
    public static final int CMD_FIELD_NUMBER = 3;
    private com.cn.common.core.model.proto.ResponseProto.CmdType cmd_;
    public boolean hasCmd() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public com.cn.common.core.model.proto.ResponseProto.CmdType getCmd() {
      return cmd_;
    }
    
    // optional bytes data = 4;
    public static final int DATA_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString data_;
    public boolean hasData() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public com.google.protobuf.ByteString getData() {
      return data_;
    }
    
    // required int32 resultCode = 5;
    public static final int RESULTCODE_FIELD_NUMBER = 5;
    private int resultCode_;
    public boolean hasResultCode() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public int getResultCode() {
      return resultCode_;
    }
    
    private void initFields() {
      hEADERFLAG_ = 21415431;
      module_ = com.cn.common.core.model.proto.ResponseProto.ModuleType.PLAYER;
      cmd_ = com.cn.common.core.model.proto.ResponseProto.CmdType.PUBLIC_CHAT;
      data_ = com.google.protobuf.ByteString.EMPTY;
      resultCode_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasResultCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, hEADERFLAG_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, module_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, cmd_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, data_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, resultCode_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, hEADERFLAG_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, module_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, cmd_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, data_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, resultCode_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.cn.common.core.model.proto.ResponseProto.Rsp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.cn.common.core.model.proto.ResponseProto.Rsp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.cn.common.core.model.proto.ResponseProto.Rsp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.cn.common.core.model.proto.ResponseProto.Rsp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.cn.common.core.model.proto.ResponseProto.Rsp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.cn.common.core.model.proto.ResponseProto.Rsp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.cn.common.core.model.proto.ResponseProto.Rsp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.cn.common.core.model.proto.ResponseProto.Rsp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.cn.common.core.model.proto.ResponseProto.Rsp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.cn.common.core.model.proto.ResponseProto.Rsp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.cn.common.core.model.proto.ResponseProto.Rsp prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.cn.common.core.model.proto.ResponseProto.RspOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cn.common.core.model.proto.ResponseProto.internal_static_com_cn_common_core_model_Rsp_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cn.common.core.model.proto.ResponseProto.internal_static_com_cn_common_core_model_Rsp_fieldAccessorTable;
      }
      
      // Construct using com.cn.common.core.model.proto.ResponseProto.Rsp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        hEADERFLAG_ = 21415431;
        bitField0_ = (bitField0_ & ~0x00000001);
        module_ = com.cn.common.core.model.proto.ResponseProto.ModuleType.PLAYER;
        bitField0_ = (bitField0_ & ~0x00000002);
        cmd_ = com.cn.common.core.model.proto.ResponseProto.CmdType.PUBLIC_CHAT;
        bitField0_ = (bitField0_ & ~0x00000004);
        data_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        resultCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cn.common.core.model.proto.ResponseProto.Rsp.getDescriptor();
      }
      
      public com.cn.common.core.model.proto.ResponseProto.Rsp getDefaultInstanceForType() {
        return com.cn.common.core.model.proto.ResponseProto.Rsp.getDefaultInstance();
      }
      
      public com.cn.common.core.model.proto.ResponseProto.Rsp build() {
        com.cn.common.core.model.proto.ResponseProto.Rsp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.cn.common.core.model.proto.ResponseProto.Rsp buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.cn.common.core.model.proto.ResponseProto.Rsp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.cn.common.core.model.proto.ResponseProto.Rsp buildPartial() {
        com.cn.common.core.model.proto.ResponseProto.Rsp result = new com.cn.common.core.model.proto.ResponseProto.Rsp(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.hEADERFLAG_ = hEADERFLAG_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.module_ = module_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.cmd_ = cmd_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.data_ = data_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.resultCode_ = resultCode_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cn.common.core.model.proto.ResponseProto.Rsp) {
          return mergeFrom((com.cn.common.core.model.proto.ResponseProto.Rsp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.cn.common.core.model.proto.ResponseProto.Rsp other) {
        if (other == com.cn.common.core.model.proto.ResponseProto.Rsp.getDefaultInstance()) return this;
        if (other.hasHEADERFLAG()) {
          setHEADERFLAG(other.getHEADERFLAG());
        }
        if (other.hasModule()) {
          setModule(other.getModule());
        }
        if (other.hasCmd()) {
          setCmd(other.getCmd());
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        if (other.hasResultCode()) {
          setResultCode(other.getResultCode());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasResultCode()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              hEADERFLAG_ = input.readInt32();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              com.cn.common.core.model.proto.ResponseProto.ModuleType value = com.cn.common.core.model.proto.ResponseProto.ModuleType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                module_ = value;
              }
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              com.cn.common.core.model.proto.ResponseProto.CmdType value = com.cn.common.core.model.proto.ResponseProto.CmdType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                cmd_ = value;
              }
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              data_ = input.readBytes();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              resultCode_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int32 HEADER_FLAG = 1 [default = 21415431];
      private int hEADERFLAG_ = 21415431;
      public boolean hasHEADERFLAG() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getHEADERFLAG() {
        return hEADERFLAG_;
      }
      public Builder setHEADERFLAG(int value) {
        bitField0_ |= 0x00000001;
        hEADERFLAG_ = value;
        onChanged();
        return this;
      }
      public Builder clearHEADERFLAG() {
        bitField0_ = (bitField0_ & ~0x00000001);
        hEADERFLAG_ = 21415431;
        onChanged();
        return this;
      }
      
      // optional .com.cn.common.core.model.ModuleType module = 2;
      private com.cn.common.core.model.proto.ResponseProto.ModuleType module_ = com.cn.common.core.model.proto.ResponseProto.ModuleType.PLAYER;
      public boolean hasModule() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.cn.common.core.model.proto.ResponseProto.ModuleType getModule() {
        return module_;
      }
      public Builder setModule(com.cn.common.core.model.proto.ResponseProto.ModuleType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        module_ = value;
        onChanged();
        return this;
      }
      public Builder clearModule() {
        bitField0_ = (bitField0_ & ~0x00000002);
        module_ = com.cn.common.core.model.proto.ResponseProto.ModuleType.PLAYER;
        onChanged();
        return this;
      }
      
      // optional .com.cn.common.core.model.CmdType cmd = 3;
      private com.cn.common.core.model.proto.ResponseProto.CmdType cmd_ = com.cn.common.core.model.proto.ResponseProto.CmdType.PUBLIC_CHAT;
      public boolean hasCmd() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public com.cn.common.core.model.proto.ResponseProto.CmdType getCmd() {
        return cmd_;
      }
      public Builder setCmd(com.cn.common.core.model.proto.ResponseProto.CmdType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        cmd_ = value;
        onChanged();
        return this;
      }
      public Builder clearCmd() {
        bitField0_ = (bitField0_ & ~0x00000004);
        cmd_ = com.cn.common.core.model.proto.ResponseProto.CmdType.PUBLIC_CHAT;
        onChanged();
        return this;
      }
      
      // optional bytes data = 4;
      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasData() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        data_ = value;
        onChanged();
        return this;
      }
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000008);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      
      // required int32 resultCode = 5;
      private int resultCode_ ;
      public boolean hasResultCode() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public int getResultCode() {
        return resultCode_;
      }
      public Builder setResultCode(int value) {
        bitField0_ |= 0x00000010;
        resultCode_ = value;
        onChanged();
        return this;
      }
      public Builder clearResultCode() {
        bitField0_ = (bitField0_ & ~0x00000010);
        resultCode_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.cn.common.core.model.Rsp)
    }
    
    static {
      defaultInstance = new Rsp(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.cn.common.core.model.Rsp)
  }
  
  public interface LoginOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string token = 2;
    boolean hasToken();
    String getToken();
  }
  public static final class Login extends
      com.google.protobuf.GeneratedMessage
      implements LoginOrBuilder {
    // Use Login.newBuilder() to construct.
    private Login(Builder builder) {
      super(builder);
    }
    private Login(boolean noInit) {}
    
    private static final Login defaultInstance;
    public static Login getDefaultInstance() {
      return defaultInstance;
    }
    
    public Login getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cn.common.core.model.proto.ResponseProto.internal_static_com_cn_common_core_model_Login_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cn.common.core.model.proto.ResponseProto.internal_static_com_cn_common_core_model_Login_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string token = 2;
    public static final int TOKEN_FIELD_NUMBER = 2;
    private java.lang.Object token_;
    public boolean hasToken() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getToken() {
      java.lang.Object ref = token_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          token_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      token_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(2, getTokenBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTokenBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.cn.common.core.model.proto.ResponseProto.Login parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.cn.common.core.model.proto.ResponseProto.Login parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.cn.common.core.model.proto.ResponseProto.Login parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.cn.common.core.model.proto.ResponseProto.Login parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.cn.common.core.model.proto.ResponseProto.Login parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.cn.common.core.model.proto.ResponseProto.Login parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.cn.common.core.model.proto.ResponseProto.Login parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.cn.common.core.model.proto.ResponseProto.Login parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.cn.common.core.model.proto.ResponseProto.Login parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.cn.common.core.model.proto.ResponseProto.Login parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.cn.common.core.model.proto.ResponseProto.Login prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.cn.common.core.model.proto.ResponseProto.LoginOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cn.common.core.model.proto.ResponseProto.internal_static_com_cn_common_core_model_Login_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cn.common.core.model.proto.ResponseProto.internal_static_com_cn_common_core_model_Login_fieldAccessorTable;
      }
      
      // Construct using com.cn.common.core.model.proto.ResponseProto.Login.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        token_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cn.common.core.model.proto.ResponseProto.Login.getDescriptor();
      }
      
      public com.cn.common.core.model.proto.ResponseProto.Login getDefaultInstanceForType() {
        return com.cn.common.core.model.proto.ResponseProto.Login.getDefaultInstance();
      }
      
      public com.cn.common.core.model.proto.ResponseProto.Login build() {
        com.cn.common.core.model.proto.ResponseProto.Login result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.cn.common.core.model.proto.ResponseProto.Login buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.cn.common.core.model.proto.ResponseProto.Login result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.cn.common.core.model.proto.ResponseProto.Login buildPartial() {
        com.cn.common.core.model.proto.ResponseProto.Login result = new com.cn.common.core.model.proto.ResponseProto.Login(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.token_ = token_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cn.common.core.model.proto.ResponseProto.Login) {
          return mergeFrom((com.cn.common.core.model.proto.ResponseProto.Login)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.cn.common.core.model.proto.ResponseProto.Login other) {
        if (other == com.cn.common.core.model.proto.ResponseProto.Login.getDefaultInstance()) return this;
        if (other.hasToken()) {
          setToken(other.getToken());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000001;
              token_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string token = 2;
      private java.lang.Object token_ = "";
      public boolean hasToken() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getToken() {
        java.lang.Object ref = token_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          token_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setToken(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        token_ = value;
        onChanged();
        return this;
      }
      public Builder clearToken() {
        bitField0_ = (bitField0_ & ~0x00000001);
        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }
      void setToken(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        token_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:com.cn.common.core.model.Login)
    }
    
    static {
      defaultInstance = new Login(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.cn.common.core.model.Login)
  }
  
  public interface RegisterOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string token = 2;
    boolean hasToken();
    String getToken();
  }
  public static final class Register extends
      com.google.protobuf.GeneratedMessage
      implements RegisterOrBuilder {
    // Use Register.newBuilder() to construct.
    private Register(Builder builder) {
      super(builder);
    }
    private Register(boolean noInit) {}
    
    private static final Register defaultInstance;
    public static Register getDefaultInstance() {
      return defaultInstance;
    }
    
    public Register getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cn.common.core.model.proto.ResponseProto.internal_static_com_cn_common_core_model_Register_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cn.common.core.model.proto.ResponseProto.internal_static_com_cn_common_core_model_Register_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string token = 2;
    public static final int TOKEN_FIELD_NUMBER = 2;
    private java.lang.Object token_;
    public boolean hasToken() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getToken() {
      java.lang.Object ref = token_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          token_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      token_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(2, getTokenBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTokenBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.cn.common.core.model.proto.ResponseProto.Register parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.cn.common.core.model.proto.ResponseProto.Register parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.cn.common.core.model.proto.ResponseProto.Register parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.cn.common.core.model.proto.ResponseProto.Register parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.cn.common.core.model.proto.ResponseProto.Register parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.cn.common.core.model.proto.ResponseProto.Register parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.cn.common.core.model.proto.ResponseProto.Register parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.cn.common.core.model.proto.ResponseProto.Register parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.cn.common.core.model.proto.ResponseProto.Register parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.cn.common.core.model.proto.ResponseProto.Register parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.cn.common.core.model.proto.ResponseProto.Register prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.cn.common.core.model.proto.ResponseProto.RegisterOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cn.common.core.model.proto.ResponseProto.internal_static_com_cn_common_core_model_Register_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cn.common.core.model.proto.ResponseProto.internal_static_com_cn_common_core_model_Register_fieldAccessorTable;
      }
      
      // Construct using com.cn.common.core.model.proto.ResponseProto.Register.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        token_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cn.common.core.model.proto.ResponseProto.Register.getDescriptor();
      }
      
      public com.cn.common.core.model.proto.ResponseProto.Register getDefaultInstanceForType() {
        return com.cn.common.core.model.proto.ResponseProto.Register.getDefaultInstance();
      }
      
      public com.cn.common.core.model.proto.ResponseProto.Register build() {
        com.cn.common.core.model.proto.ResponseProto.Register result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.cn.common.core.model.proto.ResponseProto.Register buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.cn.common.core.model.proto.ResponseProto.Register result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.cn.common.core.model.proto.ResponseProto.Register buildPartial() {
        com.cn.common.core.model.proto.ResponseProto.Register result = new com.cn.common.core.model.proto.ResponseProto.Register(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.token_ = token_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cn.common.core.model.proto.ResponseProto.Register) {
          return mergeFrom((com.cn.common.core.model.proto.ResponseProto.Register)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.cn.common.core.model.proto.ResponseProto.Register other) {
        if (other == com.cn.common.core.model.proto.ResponseProto.Register.getDefaultInstance()) return this;
        if (other.hasToken()) {
          setToken(other.getToken());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000001;
              token_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string token = 2;
      private java.lang.Object token_ = "";
      public boolean hasToken() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getToken() {
        java.lang.Object ref = token_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          token_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setToken(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        token_ = value;
        onChanged();
        return this;
      }
      public Builder clearToken() {
        bitField0_ = (bitField0_ & ~0x00000001);
        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }
      void setToken(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        token_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:com.cn.common.core.model.Register)
    }
    
    static {
      defaultInstance = new Register(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.cn.common.core.model.Register)
  }
  
  public interface MessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string msg = 1;
    boolean hasMsg();
    String getMsg();
    
    // optional string fromUser = 2;
    boolean hasFromUser();
    String getFromUser();
    
    // optional string group = 3;
    boolean hasGroup();
    String getGroup();
  }
  public static final class Message extends
      com.google.protobuf.GeneratedMessage
      implements MessageOrBuilder {
    // Use Message.newBuilder() to construct.
    private Message(Builder builder) {
      super(builder);
    }
    private Message(boolean noInit) {}
    
    private static final Message defaultInstance;
    public static Message getDefaultInstance() {
      return defaultInstance;
    }
    
    public Message getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cn.common.core.model.proto.ResponseProto.internal_static_com_cn_common_core_model_Message_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cn.common.core.model.proto.ResponseProto.internal_static_com_cn_common_core_model_Message_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string msg = 1;
    public static final int MSG_FIELD_NUMBER = 1;
    private java.lang.Object msg_;
    public boolean hasMsg() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getMsg() {
      java.lang.Object ref = msg_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          msg_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string fromUser = 2;
    public static final int FROMUSER_FIELD_NUMBER = 2;
    private java.lang.Object fromUser_;
    public boolean hasFromUser() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getFromUser() {
      java.lang.Object ref = fromUser_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          fromUser_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getFromUserBytes() {
      java.lang.Object ref = fromUser_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        fromUser_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string group = 3;
    public static final int GROUP_FIELD_NUMBER = 3;
    private java.lang.Object group_;
    public boolean hasGroup() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getGroup() {
      java.lang.Object ref = group_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          group_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getGroupBytes() {
      java.lang.Object ref = group_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        group_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      msg_ = "";
      fromUser_ = "";
      group_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasMsg()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getMsgBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getFromUserBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getGroupBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getMsgBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getFromUserBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getGroupBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.cn.common.core.model.proto.ResponseProto.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.cn.common.core.model.proto.ResponseProto.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.cn.common.core.model.proto.ResponseProto.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.cn.common.core.model.proto.ResponseProto.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.cn.common.core.model.proto.ResponseProto.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.cn.common.core.model.proto.ResponseProto.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.cn.common.core.model.proto.ResponseProto.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.cn.common.core.model.proto.ResponseProto.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.cn.common.core.model.proto.ResponseProto.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.cn.common.core.model.proto.ResponseProto.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.cn.common.core.model.proto.ResponseProto.Message prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.cn.common.core.model.proto.ResponseProto.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cn.common.core.model.proto.ResponseProto.internal_static_com_cn_common_core_model_Message_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cn.common.core.model.proto.ResponseProto.internal_static_com_cn_common_core_model_Message_fieldAccessorTable;
      }
      
      // Construct using com.cn.common.core.model.proto.ResponseProto.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        msg_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        fromUser_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        group_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cn.common.core.model.proto.ResponseProto.Message.getDescriptor();
      }
      
      public com.cn.common.core.model.proto.ResponseProto.Message getDefaultInstanceForType() {
        return com.cn.common.core.model.proto.ResponseProto.Message.getDefaultInstance();
      }
      
      public com.cn.common.core.model.proto.ResponseProto.Message build() {
        com.cn.common.core.model.proto.ResponseProto.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.cn.common.core.model.proto.ResponseProto.Message buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.cn.common.core.model.proto.ResponseProto.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.cn.common.core.model.proto.ResponseProto.Message buildPartial() {
        com.cn.common.core.model.proto.ResponseProto.Message result = new com.cn.common.core.model.proto.ResponseProto.Message(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.msg_ = msg_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.fromUser_ = fromUser_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.group_ = group_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cn.common.core.model.proto.ResponseProto.Message) {
          return mergeFrom((com.cn.common.core.model.proto.ResponseProto.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.cn.common.core.model.proto.ResponseProto.Message other) {
        if (other == com.cn.common.core.model.proto.ResponseProto.Message.getDefaultInstance()) return this;
        if (other.hasMsg()) {
          setMsg(other.getMsg());
        }
        if (other.hasFromUser()) {
          setFromUser(other.getFromUser());
        }
        if (other.hasGroup()) {
          setGroup(other.getGroup());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasMsg()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              msg_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              fromUser_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              group_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string msg = 1;
      private java.lang.Object msg_ = "";
      public boolean hasMsg() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getMsg() {
        java.lang.Object ref = msg_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          msg_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setMsg(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        msg_ = value;
        onChanged();
        return this;
      }
      public Builder clearMsg() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      void setMsg(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        msg_ = value;
        onChanged();
      }
      
      // optional string fromUser = 2;
      private java.lang.Object fromUser_ = "";
      public boolean hasFromUser() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getFromUser() {
        java.lang.Object ref = fromUser_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          fromUser_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setFromUser(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        fromUser_ = value;
        onChanged();
        return this;
      }
      public Builder clearFromUser() {
        bitField0_ = (bitField0_ & ~0x00000002);
        fromUser_ = getDefaultInstance().getFromUser();
        onChanged();
        return this;
      }
      void setFromUser(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        fromUser_ = value;
        onChanged();
      }
      
      // optional string group = 3;
      private java.lang.Object group_ = "";
      public boolean hasGroup() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getGroup() {
        java.lang.Object ref = group_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          group_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setGroup(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        group_ = value;
        onChanged();
        return this;
      }
      public Builder clearGroup() {
        bitField0_ = (bitField0_ & ~0x00000004);
        group_ = getDefaultInstance().getGroup();
        onChanged();
        return this;
      }
      void setGroup(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        group_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:com.cn.common.core.model.Message)
    }
    
    static {
      defaultInstance = new Message(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.cn.common.core.model.Message)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_cn_common_core_model_Rsp_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_cn_common_core_model_Rsp_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_cn_common_core_model_Login_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_cn_common_core_model_Login_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_cn_common_core_model_Register_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_cn_common_core_model_Register_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_cn_common_core_model_Message_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_cn_common_core_model_Message_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Response.proto\022\030com.cn.common.core.mod" +
      "el\"\254\001\n\003Rsp\022\035\n\013HEADER_FLAG\030\001 \001(\005:\0102141543" +
      "1\0224\n\006module\030\002 \001(\0162$.com.cn.common.core.m" +
      "odel.ModuleType\022.\n\003cmd\030\003 \001(\0162!.com.cn.co" +
      "mmon.core.model.CmdType\022\014\n\004data\030\004 \001(\014\022\022\n" +
      "\nresultCode\030\005 \002(\005\"\026\n\005Login\022\r\n\005token\030\002 \001(" +
      "\t\"\031\n\010Register\022\r\n\005token\030\002 \001(\t\"7\n\007Message\022" +
      "\013\n\003msg\030\001 \002(\t\022\020\n\010fromUser\030\002 \001(\t\022\r\n\005group\030" +
      "\003 \001(\t*\"\n\nModuleType\022\n\n\006PLAYER\020\001\022\010\n\004CHAT\020" +
      "\002*]\n\007CmdType\022\017\n\013PUBLIC_CHAT\020\013\022\020\n\014PRIVATE",
      "_CHAT\020\014\022\026\n\022REGISTER_AND_LOGIN\020\025\022\t\n\005LOGIN" +
      "\020\026\022\014\n\010PUSHCHAT\020eB/\n\036com.cn.common.core.m" +
      "odel.protoB\rResponseProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_cn_common_core_model_Rsp_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_cn_common_core_model_Rsp_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_cn_common_core_model_Rsp_descriptor,
              new java.lang.String[] { "HEADERFLAG", "Module", "Cmd", "Data", "ResultCode", },
              com.cn.common.core.model.proto.ResponseProto.Rsp.class,
              com.cn.common.core.model.proto.ResponseProto.Rsp.Builder.class);
          internal_static_com_cn_common_core_model_Login_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_cn_common_core_model_Login_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_cn_common_core_model_Login_descriptor,
              new java.lang.String[] { "Token", },
              com.cn.common.core.model.proto.ResponseProto.Login.class,
              com.cn.common.core.model.proto.ResponseProto.Login.Builder.class);
          internal_static_com_cn_common_core_model_Register_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_cn_common_core_model_Register_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_cn_common_core_model_Register_descriptor,
              new java.lang.String[] { "Token", },
              com.cn.common.core.model.proto.ResponseProto.Register.class,
              com.cn.common.core.model.proto.ResponseProto.Register.Builder.class);
          internal_static_com_cn_common_core_model_Message_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_com_cn_common_core_model_Message_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_cn_common_core_model_Message_descriptor,
              new java.lang.String[] { "Msg", "FromUser", "Group", },
              com.cn.common.core.model.proto.ResponseProto.Message.class,
              com.cn.common.core.model.proto.ResponseProto.Message.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
