// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Request.proto

package com.cn.common.core.model.proto;

public final class RequestProto {
  private RequestProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum ModuleType
      implements com.google.protobuf.ProtocolMessageEnum {
    PLAYER(0, 1),
    CHAT(1, 2),
    ;
    
    public static final int PLAYER_VALUE = 1;
    public static final int CHAT_VALUE = 2;
    
    
    public final int getNumber() { return value; }
    
    public static ModuleType valueOf(int value) {
      switch (value) {
        case 1: return PLAYER;
        case 2: return CHAT;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<ModuleType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ModuleType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ModuleType>() {
            public ModuleType findValueByNumber(int number) {
              return ModuleType.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return RequestProto.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final ModuleType[] VALUES = {
      PLAYER, CHAT, 
    };
    
    public static ModuleType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private ModuleType(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:com.cn.common.core.model.ModuleType)
  }
  
  public enum CmdType
      implements com.google.protobuf.ProtocolMessageEnum {
    PUBLIC_CHAT(0, 1),
    PRIVATE_CHAT(1, 2),
    PUSHCHAT(2, 101),
    ;
    
    public static final int PUBLIC_CHAT_VALUE = 1;
    public static final int PRIVATE_CHAT_VALUE = 2;
    public static final int PUSHCHAT_VALUE = 101;
    
    
    public final int getNumber() { return value; }
    
    public static CmdType valueOf(int value) {
      switch (value) {
        case 1: return PUBLIC_CHAT;
        case 2: return PRIVATE_CHAT;
        case 101: return PUSHCHAT;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<CmdType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<CmdType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CmdType>() {
            public CmdType findValueByNumber(int number) {
              return CmdType.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return RequestProto.getDescriptor().getEnumTypes().get(1);
    }
    
    private static final CmdType[] VALUES = {
      PUBLIC_CHAT, PRIVATE_CHAT, PUSHCHAT, 
    };
    
    public static CmdType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private CmdType(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:com.cn.common.core.model.CmdType)
  }
  
  public interface BodyOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required bytes data = 1;
    boolean hasData();
    com.google.protobuf.ByteString getData();
  }
  public static final class Body extends
      com.google.protobuf.GeneratedMessage
      implements BodyOrBuilder {
    // Use Body.newBuilder() to construct.
    private Body(Builder builder) {
      super(builder);
    }
    private Body(boolean noInit) {}
    
    private static final Body defaultInstance;
    public static Body getDefaultInstance() {
      return defaultInstance;
    }
    
    public Body getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RequestProto.internal_static_com_cn_common_core_model_Body_descriptor;
    }
    
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RequestProto.internal_static_com_cn_common_core_model_Body_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required bytes data = 1;
    public static final int DATA_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString data_;
    public boolean hasData() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.google.protobuf.ByteString getData() {
      return data_;
    }
    
    private void initFields() {
      data_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, data_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, data_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static Body parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static Body parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static Body parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static Body parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static Body parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static Body parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static Body parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static Body parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static Body parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static Body parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Body prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements BodyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return RequestProto.internal_static_com_cn_common_core_model_Body_descriptor;
      }
      
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return RequestProto.internal_static_com_cn_common_core_model_Body_fieldAccessorTable;
      }
      
      // Construct using com.cn.common.core.model.proto.RequestProto.Body.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        data_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Body.getDescriptor();
      }
      
      public Body getDefaultInstanceForType() {
        return Body.getDefaultInstance();
      }
      
      public Body build() {
        Body result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private Body buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        Body result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public Body buildPartial() {
        Body result = new Body(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.data_ = data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Body) {
          return mergeFrom((Body)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(Body other) {
        if (other == Body.getDefaultInstance()) return this;
        if (other.hasData()) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasData()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              data_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required bytes data = 1;
      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasData() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        data_ = value;
        onChanged();
        return this;
      }
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000001);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.cn.common.core.model.Body)
    }
    
    static {
      defaultInstance = new Body(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.cn.common.core.model.Body)
  }
  
  public interface HeadOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int32 HEADER_FLAG = 1 [default = 21415431];
    boolean hasHEADERFLAG();
    int getHEADERFLAG();
    
    // required .com.cn.common.core.model.ModuleType module = 2 [default = PLAYER];
    boolean hasModule();
    ModuleType getModule();
    
    // required .com.cn.common.core.model.CmdType cmd = 3 [default = PUBLIC_CHAT];
    boolean hasCmd();
    CmdType getCmd();
  }
  public static final class Head extends
      com.google.protobuf.GeneratedMessage
      implements HeadOrBuilder {
    // Use Head.newBuilder() to construct.
    private Head(Builder builder) {
      super(builder);
    }
    private Head(boolean noInit) {}
    
    private static final Head defaultInstance;
    public static Head getDefaultInstance() {
      return defaultInstance;
    }
    
    public Head getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RequestProto.internal_static_com_cn_common_core_model_Head_descriptor;
    }
    
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RequestProto.internal_static_com_cn_common_core_model_Head_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional int32 HEADER_FLAG = 1 [default = 21415431];
    public static final int HEADER_FLAG_FIELD_NUMBER = 1;
    private int hEADERFLAG_;
    public boolean hasHEADERFLAG() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getHEADERFLAG() {
      return hEADERFLAG_;
    }
    
    // required .com.cn.common.core.model.ModuleType module = 2 [default = PLAYER];
    public static final int MODULE_FIELD_NUMBER = 2;
    private ModuleType module_;
    public boolean hasModule() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public ModuleType getModule() {
      return module_;
    }
    
    // required .com.cn.common.core.model.CmdType cmd = 3 [default = PUBLIC_CHAT];
    public static final int CMD_FIELD_NUMBER = 3;
    private CmdType cmd_;
    public boolean hasCmd() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public CmdType getCmd() {
      return cmd_;
    }
    
    private void initFields() {
      hEADERFLAG_ = 21415431;
      module_ = ModuleType.PLAYER;
      cmd_ = CmdType.PUBLIC_CHAT;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasModule()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCmd()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, hEADERFLAG_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, module_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, cmd_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, hEADERFLAG_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, module_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, cmd_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static Head parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static Head parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static Head parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static Head parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static Head parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static Head parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static Head parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static Head parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static Head parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static Head parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Head prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements HeadOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return RequestProto.internal_static_com_cn_common_core_model_Head_descriptor;
      }
      
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return RequestProto.internal_static_com_cn_common_core_model_Head_fieldAccessorTable;
      }
      
      // Construct using com.cn.common.core.model.proto.RequestProto.Head.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        hEADERFLAG_ = 21415431;
        bitField0_ = (bitField0_ & ~0x00000001);
        module_ = ModuleType.PLAYER;
        bitField0_ = (bitField0_ & ~0x00000002);
        cmd_ = CmdType.PUBLIC_CHAT;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Head.getDescriptor();
      }
      
      public Head getDefaultInstanceForType() {
        return Head.getDefaultInstance();
      }
      
      public Head build() {
        Head result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private Head buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        Head result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public Head buildPartial() {
        Head result = new Head(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.hEADERFLAG_ = hEADERFLAG_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.module_ = module_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.cmd_ = cmd_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Head) {
          return mergeFrom((Head)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(Head other) {
        if (other == Head.getDefaultInstance()) return this;
        if (other.hasHEADERFLAG()) {
          setHEADERFLAG(other.getHEADERFLAG());
        }
        if (other.hasModule()) {
          setModule(other.getModule());
        }
        if (other.hasCmd()) {
          setCmd(other.getCmd());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasModule()) {
          
          return false;
        }
        if (!hasCmd()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              hEADERFLAG_ = input.readInt32();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              ModuleType value = ModuleType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                module_ = value;
              }
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              CmdType value = CmdType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                cmd_ = value;
              }
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int32 HEADER_FLAG = 1 [default = 21415431];
      private int hEADERFLAG_ = 21415431;
      public boolean hasHEADERFLAG() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getHEADERFLAG() {
        return hEADERFLAG_;
      }
      public Builder setHEADERFLAG(int value) {
        bitField0_ |= 0x00000001;
        hEADERFLAG_ = value;
        onChanged();
        return this;
      }
      public Builder clearHEADERFLAG() {
        bitField0_ = (bitField0_ & ~0x00000001);
        hEADERFLAG_ = 21415431;
        onChanged();
        return this;
      }
      
      // required .com.cn.common.core.model.ModuleType module = 2 [default = PLAYER];
      private ModuleType module_ = ModuleType.PLAYER;
      public boolean hasModule() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public ModuleType getModule() {
        return module_;
      }
      public Builder setModule(ModuleType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        module_ = value;
        onChanged();
        return this;
      }
      public Builder clearModule() {
        bitField0_ = (bitField0_ & ~0x00000002);
        module_ = ModuleType.PLAYER;
        onChanged();
        return this;
      }
      
      // required .com.cn.common.core.model.CmdType cmd = 3 [default = PUBLIC_CHAT];
      private CmdType cmd_ = CmdType.PUBLIC_CHAT;
      public boolean hasCmd() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public CmdType getCmd() {
        return cmd_;
      }
      public Builder setCmd(CmdType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        cmd_ = value;
        onChanged();
        return this;
      }
      public Builder clearCmd() {
        bitField0_ = (bitField0_ & ~0x00000004);
        cmd_ = CmdType.PUBLIC_CHAT;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.cn.common.core.model.Head)
    }
    
    static {
      defaultInstance = new Head(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.cn.common.core.model.Head)
  }
  
  public interface ReqOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .com.cn.common.core.model.Head head = 1;
    boolean hasHead();
    Head getHead();
    HeadOrBuilder getHeadOrBuilder();
    
    // required .com.cn.common.core.model.Body body = 2;
    boolean hasBody();
    Body getBody();
    BodyOrBuilder getBodyOrBuilder();
  }
  public static final class Req extends
      com.google.protobuf.GeneratedMessage
      implements ReqOrBuilder {
    // Use Req.newBuilder() to construct.
    private Req(Builder builder) {
      super(builder);
    }
    private Req(boolean noInit) {}
    
    private static final Req defaultInstance;
    public static Req getDefaultInstance() {
      return defaultInstance;
    }
    
    public Req getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RequestProto.internal_static_com_cn_common_core_model_Req_descriptor;
    }
    
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RequestProto.internal_static_com_cn_common_core_model_Req_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required .com.cn.common.core.model.Head head = 1;
    public static final int HEAD_FIELD_NUMBER = 1;
    private Head head_;
    public boolean hasHead() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public Head getHead() {
      return head_;
    }
    public HeadOrBuilder getHeadOrBuilder() {
      return head_;
    }
    
    // required .com.cn.common.core.model.Body body = 2;
    public static final int BODY_FIELD_NUMBER = 2;
    private Body body_;
    public boolean hasBody() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public Body getBody() {
      return body_;
    }
    public BodyOrBuilder getBodyOrBuilder() {
      return body_;
    }
    
    private void initFields() {
      head_ = Head.getDefaultInstance();
      body_ = Body.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasHead()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBody()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getHead().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getBody().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, head_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, body_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, head_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, body_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static Req parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static Req parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static Req parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static Req parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static Req parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static Req parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static Req parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static Req parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static Req parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static Req parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Req prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return RequestProto.internal_static_com_cn_common_core_model_Req_descriptor;
      }
      
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return RequestProto.internal_static_com_cn_common_core_model_Req_fieldAccessorTable;
      }
      
      // Construct using com.cn.common.core.model.proto.RequestProto.Req.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getHeadFieldBuilder();
          getBodyFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (headBuilder_ == null) {
          head_ = Head.getDefaultInstance();
        } else {
          headBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (bodyBuilder_ == null) {
          body_ = Body.getDefaultInstance();
        } else {
          bodyBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Req.getDescriptor();
      }
      
      public Req getDefaultInstanceForType() {
        return Req.getDefaultInstance();
      }
      
      public Req build() {
        Req result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private Req buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        Req result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public Req buildPartial() {
        Req result = new Req(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (headBuilder_ == null) {
          result.head_ = head_;
        } else {
          result.head_ = headBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (bodyBuilder_ == null) {
          result.body_ = body_;
        } else {
          result.body_ = bodyBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Req) {
          return mergeFrom((Req)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(Req other) {
        if (other == Req.getDefaultInstance()) return this;
        if (other.hasHead()) {
          mergeHead(other.getHead());
        }
        if (other.hasBody()) {
          mergeBody(other.getBody());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasHead()) {
          
          return false;
        }
        if (!hasBody()) {
          
          return false;
        }
        if (!getHead().isInitialized()) {
          
          return false;
        }
        if (!getBody().isInitialized()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              Head.Builder subBuilder = Head.newBuilder();
              if (hasHead()) {
                subBuilder.mergeFrom(getHead());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setHead(subBuilder.buildPartial());
              break;
            }
            case 18: {
              Body.Builder subBuilder = Body.newBuilder();
              if (hasBody()) {
                subBuilder.mergeFrom(getBody());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setBody(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .com.cn.common.core.model.Head head = 1;
      private Head head_ = Head.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          Head, Head.Builder, HeadOrBuilder> headBuilder_;
      public boolean hasHead() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public Head getHead() {
        if (headBuilder_ == null) {
          return head_;
        } else {
          return headBuilder_.getMessage();
        }
      }
      public Builder setHead(Head value) {
        if (headBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          head_ = value;
          onChanged();
        } else {
          headBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder setHead(
          Head.Builder builderForValue) {
        if (headBuilder_ == null) {
          head_ = builderForValue.build();
          onChanged();
        } else {
          headBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder mergeHead(Head value) {
        if (headBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              head_ != Head.getDefaultInstance()) {
            head_ =
              Head.newBuilder(head_).mergeFrom(value).buildPartial();
          } else {
            head_ = value;
          }
          onChanged();
        } else {
          headBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder clearHead() {
        if (headBuilder_ == null) {
          head_ = Head.getDefaultInstance();
          onChanged();
        } else {
          headBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      public Head.Builder getHeadBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getHeadFieldBuilder().getBuilder();
      }
      public HeadOrBuilder getHeadOrBuilder() {
        if (headBuilder_ != null) {
          return headBuilder_.getMessageOrBuilder();
        } else {
          return head_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          Head, Head.Builder, HeadOrBuilder>
          getHeadFieldBuilder() {
        if (headBuilder_ == null) {
          headBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              Head, Head.Builder, HeadOrBuilder>(
                  head_,
                  getParentForChildren(),
                  isClean());
          head_ = null;
        }
        return headBuilder_;
      }
      
      // required .com.cn.common.core.model.Body body = 2;
      private Body body_ = Body.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          Body, Body.Builder, BodyOrBuilder> bodyBuilder_;
      public boolean hasBody() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public Body getBody() {
        if (bodyBuilder_ == null) {
          return body_;
        } else {
          return bodyBuilder_.getMessage();
        }
      }
      public Builder setBody(Body value) {
        if (bodyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          body_ = value;
          onChanged();
        } else {
          bodyBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder setBody(
          Body.Builder builderForValue) {
        if (bodyBuilder_ == null) {
          body_ = builderForValue.build();
          onChanged();
        } else {
          bodyBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder mergeBody(Body value) {
        if (bodyBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              body_ != Body.getDefaultInstance()) {
            body_ =
              Body.newBuilder(body_).mergeFrom(value).buildPartial();
          } else {
            body_ = value;
          }
          onChanged();
        } else {
          bodyBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder clearBody() {
        if (bodyBuilder_ == null) {
          body_ = Body.getDefaultInstance();
          onChanged();
        } else {
          bodyBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      public Body.Builder getBodyBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getBodyFieldBuilder().getBuilder();
      }
      public BodyOrBuilder getBodyOrBuilder() {
        if (bodyBuilder_ != null) {
          return bodyBuilder_.getMessageOrBuilder();
        } else {
          return body_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          Body, Body.Builder, BodyOrBuilder>
          getBodyFieldBuilder() {
        if (bodyBuilder_ == null) {
          bodyBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              Body, Body.Builder, BodyOrBuilder>(
                  body_,
                  getParentForChildren(),
                  isClean());
          body_ = null;
        }
        return bodyBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:com.cn.common.core.model.Req)
    }
    
    static {
      defaultInstance = new Req(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.cn.common.core.model.Req)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_cn_common_core_model_Body_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_cn_common_core_model_Body_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_cn_common_core_model_Head_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_cn_common_core_model_Head_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_cn_common_core_model_Req_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_cn_common_core_model_Req_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rRequest.proto\022\030com.cn.common.core.mode" +
      "l\"\024\n\004Body\022\014\n\004data\030\001 \002(\014\"\240\001\n\004Head\022\035\n\013HEAD" +
      "ER_FLAG\030\001 \001(\005:\01021415431\022<\n\006module\030\002 \002(\0162" +
      "$.com.cn.common.core.model.ModuleType:\006P" +
      "LAYER\022;\n\003cmd\030\003 \002(\0162!.com.cn.common.core." +
      "model.CmdType:\013PUBLIC_CHAT\"a\n\003Req\022,\n\004hea" +
      "d\030\001 \002(\0132\036.com.cn.common.core.model.Head\022" +
      ",\n\004body\030\002 \002(\0132\036.com.cn.common.core.model" +
      ".Body*\"\n\nModuleType\022\n\n\006PLAYER\020\001\022\010\n\004CHAT\020" +
      "\002*:\n\007CmdType\022\017\n\013PUBLIC_CHAT\020\001\022\020\n\014PRIVATE",
      "_CHAT\020\002\022\014\n\010PUSHCHAT\020eB.\n\036com.cn.common.c" +
      "ore.model.protoB\014RequestProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_cn_common_core_model_Body_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_cn_common_core_model_Body_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_cn_common_core_model_Body_descriptor,
              new String[] { "Data", },
              Body.class,
              Body.Builder.class);
          internal_static_com_cn_common_core_model_Head_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_cn_common_core_model_Head_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_cn_common_core_model_Head_descriptor,
              new String[] { "HEADERFLAG", "Module", "Cmd", },
              Head.class,
              Head.Builder.class);
          internal_static_com_cn_common_core_model_Req_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_cn_common_core_model_Req_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_cn_common_core_model_Req_descriptor,
              new String[] { "Head", "Body", },
              Req.class,
              Req.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
